language: go
dist: xenial

go:
  - 1.8
  # - 1.9

before_install:
  - gofmt -s -d ./cmd ./lib 2>&1 | tee gofmt.diff
  # `-s` is true if the file exists and has size > 0. Invert.
  - [ ! -s gofmt.diff ]
  - go get github.com/Masterminds/glide
  - glide --version
  - glide install

install:
  - GOOS=linux GOARCH=amd64 go build ./cmd/dlv
  - GOOS=darwin GOARCH=amd64 go build ./cmd/dlv

script:
  - go test -v ./lib/

notifications:
  email: false
